### ISSUE TITLE
Is it possible to buy a board anywhere?

### ISSUE THREAD

**Issue by mgiaco** [FPGAwars/icezum#36]

**Comment by Obijuan** [comment]
Hi!

In a week or so we will manage another mini-crowdfunding for a second batch (100 boards). It will be launch in the FPGAwars list (in spanish):

https://groups.google.com/forum/#!forum/fpga-wars-explorando-el-lado-libre

**Comment by mgiaco** [comment]
Okay thanks. I would be great if you can post it here because i do not speak spanish. 
many thanks
