### ISSUE TITLE
order?

### ISSUE THREAD

**Issue by phil123456** [FPGAwars/icezum#37]
hi ,

I cant find any web site to order these....

**Comment by Obijuan** [comment]
Hi,

Currently is not on sale. We are organizing small local crowdfundings for funding the batches. Batch 1 was finished (110 units). Now we are manufacturing the Batch 2 (250 units). The backers are helping us on the FPGAwars list (but i is only in spanish).

Is it possible that for the following batches we launch a more global crowdfunding compain

**Comment by moebiussurfing** [comment]
Hola buenas, me gustaría participar en el crowfounding y adquirir alguna unidad, es posible? gracias

**Comment by 1138-4EB** [comment]
> Hola buenas, me gustaría participar en el crowfunding y adquirir alguna unidad, es posible? gracias

https://groups.google.com/forum/#!topic/fpga-wars-explorando-el-lado-libre/a5mmxIj4IcM
https://groups.google.com/forum/#!topic/fpga-wars-explorando-el-lado-libre/wOaLSpkVSII
